version: '3.7'

services:

  mysql:
    container_name: timesheet_mysql
    image: mysql:8.0.23
    platform: linux/amd64
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    security_opt:
      - seccomp:unconfined
    networks:
      - timesheet_db_networks

  adminer:
    container_name: adminder_example
    image: adminer
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - timesheet_db_networks

  api:
    container_name: timesheet_api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    ports: 
      - 9000:9000
    command: [sh, -c, 'npm run start:dev']
    depends_on:
      - mongodb
      - redis
      - mysql
    networks:
      - timesheet_db_networks
      - timesheet_cache_networks
      - timesheet_web_networks
    volumes:
      - ./api/src:/app/src
      - ./api/tests:/app/tests

  client:
    container_name: timesheet_client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    ports: 
      - 3000:3000
    command: [sh, -c, 'npm run serve']
    depends_on:
      - api
    networks:
      - timesheet_web_networks
    volumes:
      - ./client/src:/app/src

  mongodb:
    container_name: timesheet_mongodb
    image: mongo:4.4
    volumes:
      - ./.docker/data/mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - timesheet_db_networks
  
  redis:
    container_name: timesheet_redis
    image: redis:5-alpine
    volumes:
      - ./.docker/data/redis:/data
    restart: unless-stopped
    networks:
      - timesheet_cache_networks

    
    
networks:
  timesheet_web_networks:
      driver: bridge
  timesheet_db_networks:
    driver: bridge
  timesheet_cache_networks:
    driver: bridge