FROM node:16-alpine AS builder

WORKDIR /app

COPY . .

RUN npm install

FROM builder AS prod

RUN npm install

RUN npm i -g pm2

# CMD [ "pm2-runtime", "ecosystem.config.js", "--env", "production" ]

CMD ["sh", "-c", "pm2-runtime ecosystem.config.js --env production"]
