name: Dev-Workflow 

on:
  push:
    branches: [develop]
  
  pull_request:
    branches: [develop]

jobs:
  run-linters-api:
    name: Run Linters Api
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Setup Nodejs 
        uses: actions/setup-node@v1
        with:
          node-version: 19

      - name: Intsall Node.js Dependencies
        run: cd ./api && npm ci
      
      - name: Run Linters
        run: cd ./api && npm run lint:fix
        continue-on-error: true

      - name: Verify Linted
        run: echo "Linted BackEnd"

  run-linters-client:
    name: Run Linters Client
    needs: [run-linters-api]
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Setup Nodejs 
        uses: actions/setup-node@v1
        with:
          node-version: 19

      - name: Intsall Node.js Dependencies
        run: cd ./client && npm ci
      
      - name: Run Linters
        run: cd ./client && npm run lint:fix
        continue-on-error: true

      - name: Verify Linted
        run: echo "Linted FrontEnd"

  