name: Lint

on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./api
    
jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Setup Nodejs 
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Intsall Node.js Dependencies
        run: npm ci
      
      - name: Run Linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true

  